TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a

TARGET_BOARD_PLATFORM := sm8150

BOARD_FLASH_BLOCK_SIZE := 2048
BOARD_BOOTIMAGE_PARTITION_SIZE := 37748736
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 50331648

TARGET_PREBUILT_KERNEL := device/samsung/beyond2qlte/prebuilt/Image.gz-dtb

OF_SUPPORT_ADB_SIDELOAD := true
OF_SUPPORT_TWRP_THEME := true
OF_NO_REBOOT_RECOVERY := true
