$(call inherit-product-if-exists, vendor/recovery/bootable/recovery/twrp.mk)

TARGET_BOARD_PLATFORM := sm8150
TARGET_BOARD_PLATFORM_GPU := qcom-adreno640

TARGET_ARCH := arm64
TARGET_CPU_ABI := arm64-v8a

BOARD_BOOTIMAGE_PARTITION_SIZE := 37748736
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 50331648
BOARD_FLASH_BLOCK_SIZE := 2048

TW_THEME := portrait_hdpi
TW_INCLUDE_CRYPTO_SAMSUNG := true
TW_DEFAULT_BRIGHTNESS := 2200
